### ISSUE TITLE
Questions for providing value setting API based on Array index

### ISSUE THREAD

**Issue by ppeeou** [yorkie-team/yorkie#215]
**Description**:

Before implementing the value setting API based on Array index, I have a question to ask
related https://github.com/yorkie-team/yorkie-js-sdk/issues/191

Our strategy is to set value at the value position of `createdAt` in the array index.

However, if the above strategy is used in the current code, the following issue bellow

```go
// base array
d1.Update(func(root *proxy.ObjectProxy) error {
	root.SetNewArray("k1").AddInteger(0, 1, 2)
	return nil
})
c1.Sync(ctx)
c2.Sync(ctx)

d1.Update(func(root *proxy.ObjectProxy) error {
	root.GetArray("k1").AddInteger(0, 4)
	assert.Equal(t, `{"k1":[0,4,1,2]}`, root.Marshal())
	return nil
})

d2.Update(func(root *proxy.ObjectProxy) error {
	root.GetArray("k1").SetValue(1, 5)
	assert.Equal(t, `{"k1":[0,5,2]}`, root.Marshal())
	return nil
})

c1.Sync(ctx)
c2.Sync(ctx)
c1.Sync(ctx)
assert.Equal(t, `{"k1":[0,4,5,2]}`, d1.Marshal()) // expected value
assert.Equal(t, `{"k1":[0,5,4,2]}`, d2.Marshal()) // but 😭
```

`[0, 4, 5, 2]` are expected values. But the value of d2 is  `[ 0, 5, 4, 2 ]`.
The reason is that `InsertIntegerAfter` compares the index's next node `createdAt` and puts it after createdAt that is larger than itself.

https://github.com/yorkie-team/yorkie/blob/main/pkg/document/json/rga_tree_list.go#L306

array `[0(t0),1(t1),2(t2)]`

d1 case
1. In d1, `add operation` is applied first.
`d1.InsertIntegerAfter(0, 4)`
 -> `[0(t0),4(t3),1(t1),2(t2)]`
 2. `setIndex` is applied to create the desired value.
`d1.setIndex( 1, 5 )`
 -> `[0(t0),4(t3),5(t4),2(t2)]`

However
d2 case
1. In d2, `setIndex operation` is applied first.
`d2.setIndex( 1, 5 )`
-> `[0(t0),5(t4),2(t2)]`

2. `add operation` applies, but `createdAt` of add operation puts t3 after 5.
`d2.InsertIntegerAfter(0, 4)`
-> `[0(t0),5(t4),4(t3),2(t2)]`

In the present state, The commutative law does not hold.

**Why**:

**Comment by hackerwins** [comment]
Thanks for the detailed investigation. There seems to be an unexpected commutative property problem between InsertOperation and SetOperation. We should spend a little more time thinking about the algorithm and proceed.

**Comment by hackerwins** [comment]
@ppeeou, @mojosoeun 
I've been thinking about this issue a bit more.

The cause of the problem described in this issue is that we use a mix of **element positioning time** and **element creation time** in the array(Currently, we only update `movedAt` when an element is moved, so we take the positioning time of the unmoved element from `createdAt`).

I think that the problem will be solved by expressing the time the element was positioned in `movedAt`, even if the position of the element is not moved. Even if an element is newly replaced with SetOperation, the positioning time of the element in the array is recorded as the previous time.

**Comment by ppeeou** [comment]
oh...🤩  I'll try it as you said

**Comment by hackerwins** [comment]
We will consider this feature again in the future.
