### ISSUE TITLE
Allows only authenticated users to use the cluster's admin commands

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#377]
**Description**:

Allows only authenticated users to use the cluster's admin commands.

Tasks

- [x] Add CRUDs for UserInfo
- [x] Create a default user if it does not exist when running the server
- [x] Add Signup and Login APIs
- [x] Add token manager(JWT)
- [x] Add auth interceptors for the admin server
- [x] Add auth interceptors for admin clients both web and CLI
- [x] Add login command for CLI
- [x] Add Signup and Login pages to Yorkie House
- [ ] Add logout command for CLI
- [ ] ~Add roles between UserInfo and ProjectInfo~
- [ ] ~Integrate with other authentication systems~

**Why**:
- For security reasons, access to admin API is restricted to authorized users only.

**Comment by chromato99** [comment]
Could I try to add lgout command for CLI?

**Comment by chromato99** [comment]
Ah, there seems to be a problem that the token does not expire by simply deleting the token from config.json when logging out...
I think it need more thinking...

**Comment by kpfaulkner** [comment]
This seems to be working for me (Win11). I can see the config.json getting modified and following commands fail due to unauthenticated response.

What's the scenario you're seeing where this fails?

Or are you referring to the the claims on the server side are not being expired?

(disclaimer, I'm brand new to Yorkie and just digging through the code to see how things piece together).

**Comment by hackerwins** [comment]
The logout command will be covered in #488.
