### ISSUE TITLE
Implement validation for Document Key

### ISSUE THREAD

**Issue by chacha912** [yorkie-team/yorkie#457]
**Description**: 
Currently, there are no restrictions on the document key when creating a document. 
Any characters can be used and no errors will occur. 

However, this causes issues when using the [Dashboard](https://github.com/yorkie-team/dashboard),
as the key is used in the URL and inappropriate characters can cause problems.
- Dashboard URL example - document search: 
`https://yorkie.dev/dashboard/projects/project-name/documents/document-key`

---

1. It is necessary to add rules for the allowed characters in the document key.
  - maximum length restrictions: ex) `From 4 to 30 characters in length`
  - can be used as a slug: ex) `Only contains letters, numbers, and the following characters: - . _ ~`
  - related https://github.com/yorkie-team/yorkie/pull/345
2. It would be helpful to provide a method to shorten the key.
  - For example, if the key is made by combining project, block, edit, file like `prj-block-edit-file`, it is inconvenient because the key is too long. If there is a way to shorten the key, it would be helpful for users.

**Why**: Currently, any characters can be used as the document key. It can cause problems when using the dashboard.

**Comment by easylogic** [comment]
I am wondering how to define the document key. A few things are a little ambiguous.

1. Why is it a problem when reading the document key in the form of a url in the dashboard?
  * I think it will be okay if you wrap this in the form of encodeURIComponent and send it as url.
  * Wouldn't it be better to access it by id instead of documentKey?
    * projects/{projectName}/documents/{id}
2. It's ok to have a format in the document key
3. So, where should I check this form?
  * When creating the first document object, yorkie.Document(key)
    * This will require all validation logic on individual clients.
  * Second, when attach (doc)
    * When attaching a document, the server first searches for the document, and if not, it is upsert to mongo db. At this time, 
    * if the key is not valid, an error occurs.
4. Will there be any issues with the document key after that?
  * codepair migration issue (codepair is forcing codepair$ as prefix)
  * How to keep redirects on migration ?
  * Does changing documentKey affect snapshot and other internal data?
  * Does it affect history as well?
  * Could it also affect the pub/sub structure?
