### ISSUE TITLE
Introduce sharding rules to MongoDB collections

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#530]
**Description**:

This description is written by @sejongk

To address the load concentrated on the database, we need to introduce a MongoDB Sharded Cluster and apply appropriate sharding rules to the collections for a solution.

- Indexes: https://github.com/yorkie-team/yorkie/blob/main/server/backend/database/mongo/indexes.go
- Note: https://codepair.yorkie.dev/khfbyv

**Why**:

The Yorkie cluster stores almost all data, including documents and changes representing edits, in MongoDB. It has been observed that in real-world service scenarios, the majority of the load is concentrated on the database rather than the application servers, as was the case with Yorkie's predecessor, Kaleido.

**Comment by sejongk** [comment]
We need to determine which sharding method is appropriate for Yorkie and what kinds of sharding method MongoDB supports.
 For example, ranged sharding would be efficient if a range of documents is frequently queried. Additionally, hash sharding would be ideal for massively-scalable workloads because it distributes data evenly.
