### ISSUE TITLE
SDKs for various environments

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#54]
**Description**:

We provide Go Client and JS SDK. It would be good to implement the SDK in the following order.

- [x] yorkie: Go client
- [x] yorkie-js-sdk
- [x] yorkie-rust-sdk
- [x] yorkie-ios-sdk
- [x] yorkie-android-sdk

**Why**:

Users can use Yorkie in a variety of environments.

**Comment by gedw99** [comment]
Dart Flutter would be cool.
FLutter runs on Mobile, Desktop and Web from just the dart code..

**Comment by hackerwins** [comment]
@gedw99 I didn't know about Dart Flutter, but thanks for letting me know. And thank you for your interest in Yorkie. Providing a Flutter SDK seems like a good idea.

But these days, I am working on the server, so it is difficult to me to directly develop the Flutter SDK for now. When someone is working on the Flutter SDK, I think we can talk and I can help the one to implement Yorkie's algorithm.

**Comment by gedw99** [comment]
I can do the flutter layer.

Your architecture is very similar to our project, since you use envoy and grpc-web etc.

The team is in Telegram btw:
https://t.me/GetCourageNow_dev

I am really interested in the CRT Server and offline editing, and think i can help with it since we all program in golang and flutter

**Comment by gedw99** [comment]
I managed to get the Golang girlie client running inside flutter web and native ( mobiles and desktop ).

I had to do some very bad hacks though. I just wanted to see how it behaved.

I am trying out a client side dB called genii.
It’s Golang based and can cross compile to wasm. This is a doc store with sql abilities

**Comment by gedw99** [comment]
Sorry I pressed return too early. The protobuf pub sub or looks really nice btw.

For the ja and react clients do you have a client side dB ?

**Comment by joe-getcouragenow** [comment]
So for Dart  then everything in the following will need to be ported to Dart in order to use this in flutter ?
"github.com/yorkie-team/yorkie/pkg/document"
"github.com/yorkie-team/yorkie/pkg/document/key"
"github.com/yorkie-team/yorkie/pkg/document/time"

**Comment by hackerwins** [comment]
@joe-getcouragenow That's right. Under the `yorkie/pkg/document` package you mentioned, there is Document logic composed of CRDT. In addition, the logic for the Client is required.

I think it would be helpful to figure out the scope of developing SDK based on the JS SDK.
https://github.com/yorkie-team/yorkie-js-sdk/tree/master/src

**Comment by joe-getcouragenow** [comment]
> @joe-getcouragenow That's right. Under the `yorkie/pkg/document` package you mentioned, there is Document logic composed of CRDT. In addition, the logic for the Client is required.
> 
> I think it would be helpful to figure out the scope of developing SDK based on the JS SDK.
> https://github.com/yorkie-team/yorkie-js-sdk/tree/master/src

Not sure what your mean by the above. 

---

There is another GUI Framework i am using that is 100% golang based. It would be a really good candidate as it compiles ot all Mobiles, Desktops and Web ( as WASM).

https://git.sr.ht/~eliasnaur/gio/tree/master

Good Mirror: https://github.com/theclapp/gio-mirror

Issue: https://todo.sr.ht/~eliasnaur/gio

install: https://gioui.org/doc/install

**Comment by hackerwins** [comment]
I mean, it would be helpful to develop new SDK in other environments or languages ​​with reference to the already developed JS SDK.

**Comment by joe-getcouragenow** [comment]
got it.

How about we WASM the golang code above ?
I am not joking... 

from your JS layer its easy to use.
From flutter, and many others it easy to us.

Its a good candidate because its simple code, and you just need to inject the data you get over the wire into it and get the result out. Very good worker architecture.

If you dont like this we can also do it the traditional way...

**Comment by joe-getcouragenow** [comment]
![Screenshot 2020-06-20 at 12 30 26](https://user-images.githubusercontent.com/59567750/85199697-dd6d1f00-b2f1-11ea-9f4b-40256c755b4b.png)

code:
https://github.com/rodydavis/flutter_wasm_interop

**Comment by hackerwins** [comment]
@gedw99 There is no local DB on the JS SDK yet. Later, when we introduce local DB, we can store each property of the Document. I think it will be easy because we use Protobuf.

**Comment by hackerwins** [comment]
@joe-getcouragenow I don't know about WASM yet, but I think it's a good idea if it can be used in multiple environments.

**Comment by gedw99** [comment]
So I think in order to support any client envoy proxy will be needed. You can easily run it in the docker compose.

This allows grpc to work with web ( grpc-web ) and native ( grpc ).

It will also make the system scale horizontally because envoy proxy runs as s sidecar to each server service. You can update the envoy config for all instances using the envoy grpc API.

This will mean that when you codegen from the grpc protobufs the generated code for all clients ( any language or web or native ) will just work.

https://github.com/envoyproxy/envoy/blob/master/examples/front-proxy/docker-compose.yaml

Also Auth and authz can be done with envoy too 
https://medium.com/@ricklee_10931/envoy-external-authorization-a-simple-example-d50ef2ede631

The rest or your Architecture remain mostly untouched . In fact alot of the code on the clients and servers will not be needed due to the code generation.

**Comment by hackerwins** [comment]
@gedw99 Thank you for the explanation. I wonder if you are going to work on what you said.

**Comment by joe-getcouragenow** [comment]
> @gedw99 Thank you for the explanation. I wonder if you are going to work on what you said.

Awesome....

I think the first thing is to move the docker compose that has envoy in it into the yorkie repo.
Its currently in yorkie-js-sdk which is the wrong place because envoy is used for everything and not just JS.
SO then then the server is ALWAS running envoy, and not just for the JS.

@hackerwins i think that pretty easy to do on your side first  ?

---

Then i think automatic TLS is needed, so that its very easy to boot an Envoy with LTS.  
- "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext"

Also the envoy config should be setup to run as an edge proxy, as its not being used as a Services mesh in the Yorkie context right ?
https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge
- Yu can see if has the TLS there also.

Once the Yorkie repo has this then its easy to add autocert integration for Lets Encyprt.
- Later we can use Mongo DB to store the certs. This is needed for running more than one yorkie.

I am working on that now.

----

then i think the WASM of the types using tinygo is next. These types:
"github.com/yorkie-team/yorkie/pkg/document"
"github.com/yorkie-team/yorkie/pkg/document/key"
"github.com/yorkie-team/yorkie/pkg/document/time"

Because those types are so simple and have no reflection, tinygo can do it.

I am working on that now.

---

Finally...

At this point we can support all clients types and all languages.
- everyone can handle grpc / protobuf
- everyone can load WASM ( browser or non browser ) these days. See: https://github.com/wasmerio/wasmer#language-integrations

**Comment by joe-getcouragenow** [comment]
All:

let me know if you want to change anything Or if you like this approach

**Comment by gedw99** [comment]
Sounds good to me 👍

Background on auto TLS :
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/ssl

We need a provider. Probably autocert like what the golang team uses ?

**Comment by joe-getcouragenow** [comment]
@hackerwins 

> you

@hackerwins 
I started to work on this, but as i got into it i realised that there are other things that need to be done first.
I will chat to you on Slack about these if you dont mind.

**Comment by hackerwins** [comment]
Lately, I've been interested in [Rust](https://www.rust-lang.org/). It would be nice to implement Rust SDK after the [JS SDK](https://github.com/yorkie-team/yorkie-js-sdk).

**Comment by gedw99** [comment]
@hackerwins you might be interested in the GIO golang gui.
I was using flutter and changed to using gio.

its 100% golang for Web, Desktop and Mobile. The underlying design is like Flutter in that its a canvas that the GPU ( webgl canvas in webs case )  renders to.

https://gioui.org/

The advantage with yorkie is of course that the backend and frontend gui is all in golang, so it can make things easier. Especially from an SDK point of view because you can share code on both side.

If you want more info let me know ..

https://github.com/planetdecred/godcr is a good example of a big app btw

**Comment by hackerwins** [comment]
We created `yorkie-ios-sdk` and `yorkie-android-sdk` repositories.

- https://github.com/yorkie-team/yorkie-android-sdk
- https://github.com/yorkie-team/yorkie-ios-sdk
