### ISSUE TITLE
Housekeeping is Not Working Properly on Single Project

### ISSUE THREAD

**Issue by krapie** [yorkie-team/yorkie#744]
**What happened**:

Housekeeping is not working properly on single project(default project).

I think this is because `listProjectInfos()` queries projects on `$gt`(greater than) option. If there is only one project, the `listProjectInfos()` function queries for a larger `_id`, which excludes that single project. This will not fetch any projects, leading to empty candidates list for deactivation.

https://github.com/yorkie-team/yorkie/blob/8987b45546289617d40586a5335ebf0a55161b8b/server/backend/database/mongo/client.go#L244-L261

It seems like memDB is also causing the same problem.

https://github.com/yorkie-team/yorkie/blob/8987b45546289617d40586a5335ebf0a55161b8b/server/backend/database/memory/database.go#L228-L260

MemDB is fetching projects successfully because it uses `LowerBound()`, but it skips appending project when `i == 0 && info.ID == housekeepingLastProjectID`.

**What you expected to happen**:

Housekeeping fetches single project and clients for deactivation.

**How to reproduce it (as minimally and precisely as possible)**:

Simply run server with mongoDB attached and project deactivation threshold(`--client-deactivate-threshold`) with smaller interval (ex: `10s`), and create clients for housekeeping.

**Anything else we need to know?**:

**Environment**:
- Operating system: `Any`
- Browser and version: `Any`
- Yorkie version (use `yorkie version`): `v0.4.11`
- Yorkie JS SDK version: `v.0.4.11`

**Comment by devleejb** [comment]
I am interested in this issue. Can I work on it?

**Comment by hackerwins** [comment]
Sure. If you have any questions, feel free to let me know.

**Comment by devleejb** [comment]
I suspect that the issue arises from an unintended assignment to the last housekeepingLastProjectID during the process of finding candidates.

The value of `housekeepingLastProjectID` changes due to the following code. In cases where `projectFetchSize` is equal to the total number of existing projects, `housekeepingLastProjectID` becomes the ID of the last project. Consequently, in the next `FindDeactivateCandidates` call, no projects can be fetched because `housekeepingLastProjectID` is set to the last project. It can be checked by test code below.

```go
t.Run("housekeeping should work on single project", func(t *testing.T) {
  ctx := context.Background()
  
  clientDeactivateThreshold := "0s"
  
  userInfo, err := memdb.CreateUserInfo(ctx, "test", "test")
  assert.NoError(t, err)
  
  project, err := memdb.CreateProjectInfo(ctx, database.DefaultProjectName, userInfo.ID, clientDeactivateThreshold)
  assert.NoError(t, err)
  
  client, err := memdb.ActivateClient(ctx, project.ID, t.Name())
  assert.NoError(t, err)
  
  lastProjectID := database.DefaultProjectID
  
  lastProjectID, candidates, err := memdb.FindDeactivateCandidates(
	  ctx,
	  10,
	  1,
	  lastProjectID,
  )
  assert.NoError(t, err)
  assert.Len(t, candidates, 1)
  assert.Contains(t, candidates, client)
  
  lastProjectID, candidates, err = memdb.FindDeactivateCandidates(
	  ctx,
	  10,
	  1,
	  lastProjectID,
  )
  assert.NoError(t, err)
  assert.Len(t, candidates, 0) // Should be 1
  assert.NotContains(t, candidates, client)
  
  _, candidates, err = memdb.FindDeactivateCandidates(
	  ctx,
	  10,
	  1,
	  lastProjectID,
  )
  assert.NoError(t, err)
  assert.Len(t, candidates, 1)
  assert.Contains(t, candidates, client)
})
```


So, I think the issue can be easily addressed by modifying the condition in the database from `len(projects) < projectFetchSize` to `len(projects) <= projectFetchSize`. However, I've noticed that `FindDeactivateCandidates` exists in the database interface, resulting in duplicated logic for both mongo and memorydb.
I'm curious about the design intent here. I think that `listProjectInfos` should be made public in the Database Interface, and `FindDeactivateCandidates` should be integrated into the housekeeping logic.

**Comment by devleejb** [comment]
``` go
func (d *DB) listProjectInfos(
	_ context.Context,
	pageSize int,
	housekeepingLastProjectID types.ID,
) ([]*database.ProjectInfo, error) {
    // Do something...
}
```

How about renaming this function to `listProjectInfosGreaterThan`? This function is used only in `FindDeactivateCandidates` and searches for projects after `housekeepingLastProjectID` by the specified `pageSize`. The current function name does not seem to accurately convey this role.

**Comment by krapie** [comment]
Thank you for clarifying the actual problem of this issue.

Modifying to circular form & clarifying function name seems like a good idea (`listProjectInfosGreaterThan()` name looks like Spring Data JPA though 😄).
